on:
  push:
    branches:
      - develop

jobs:
  dotnet-publish:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v5

      - name: sonarqube cloud integration
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Deepthichintha_nopCommerce
            -Dsonar.organization=deepthichintha
            -Dsonar.host.url=https://sonarcloud.io
      - name: dotnet installation
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.100"
      - name: this is my dotnet project
        run: dotnet publish -c release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
